<a href="https://colab.research.google.com/github/olivocdz-cmd/Programacion1/blob/main/Parcial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Carlos Diaz - 2192895
Parcial II

Parte II
Instrucción 1

In [18]:
import numpy as np

In [19]:
np.random.seed(0)
datos = np.random.randint(131, 194, 50)
datos

array([175, 178, 184, 131, 134, 190, 134, 170, 140, 150, 152, 181, 167,
       154, 137, 155, 155, 143, 189, 132, 169, 170, 154, 177, 155, 148,
       168, 156, 144, 139, 140, 151, 182, 147, 182, 136, 193, 146, 178,
       131, 149, 166, 155, 180, 182, 160, 150, 150, 145, 170])

In [29]:
datos[datos > 160]

array([175, 178, 184, 190, 170, 181, 167, 189, 169, 170, 177, 168, 182,
       182, 193, 178, 166, 180, 182, 170])

In [91]:
import pandas as pd
datos_pd = pd.DataFrame({'Analisis': [175, 178, 184, 131, 134, 190, 134, 170, 140, 150, 152, 181, 167,
       154, 137, 155, 155, 143, 189, 132, 169, 170, 154, 177, 155, 148,
       168, 156, 144, 139, 140, 151, 182, 147, 182, 136, 193, 146, 178,
       131, 149, 166, 155, 180, 182, 160, 150, 150, 145, 170]})
datos_pd.describe()

         Analisis
count   50.000000
mean   158.480000
std     17.769775
min    131.000000
25%    145.250000
50%    155.000000
75%    173.750000
max    193.000000

Al media de los

In [105]:

import pandas as pd
x = [175, 178, 184, 131, 134, 190, 134, 170, 140, 150, 152, 181, 167,
       154, 137, 155, 155, 143, 189, 132, 169, 170, 154, 177, 155, 148,
       168, 156, 144, 139, 140, 151, 182, 147, 182, 136, 193, 146, 178,
       131, 149, 166, 155, 180, 182, 160, 150, 150, 145, 170]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)

           0
0   0.929669
1   1.098495
2   1.436147
3  -1.546446
4  -1.377620
5   1.773799
6  -1.377620
7   0.648292
8  -1.039968
9  -0.477215
10 -0.364664
11  1.267321
12  0.479466
13 -0.252113
14 -1.208794
15 -0.195838
16 -0.195838
17 -0.871142
18  1.717523
19 -1.490171
20  0.592017
21  0.648292
22 -0.252113
23  1.042219
24 -0.195838
25 -0.589765
26  0.535741
27 -0.139563
28 -0.814867
29 -1.096243
30 -1.039968
31 -0.420939
32  1.323596
33 -0.646041
34  1.323596
35 -1.265069
36  1.942625
37 -0.702316
38  1.098495
39 -1.546446
40 -0.533490
41  0.423191
42 -0.195838
43  1.211045
44  1.323596
45  0.085539
46 -0.477215
47 -0.477215
48 -0.758591
49  0.648292

Instruccion 2

In [106]:
df1 = pd.DataFrame({"Nombre": ["Amanda", "Sofía", "Camilo", "Paula", "David"],
                   "Edad": [21, 22, 30, 19, 30],
                   "Nota": [4.5, 4.8, 3.9, 4.2, 3.9],
                   "Sexo": ["F", "F", "M", "F", "M"],
                   "Ciudad": ["Santiago", "Concepción", "Valdivia", "Bogotá", "Barcelona"]
                   })
df1

   Nombre  Edad  Nota Sexo      Ciudad
0  Amanda    21   4.5    F    Santiago
1   Sofía    22   4.8    F  Concepción
2  Camilo    30   3.9    M    Valdivia
3   Paula    19   4.2    F      Bogotá
4   David    30   3.9    M   Barcelona

In [107]:
df1.head(3)

   Nombre  Edad  Nota Sexo      Ciudad
0  Amanda    21   4.5    F    Santiago
1   Sofía    22   4.8    F  Concepción
2  Camilo    30   3.9    M    Valdivia

In [108]:
df1["Edad"].apply(lambda x: x + 1)

0    22
1    23
2    31
3    20
4    31
Name: Edad, dtype: int64

In [56]:
grupo = df1.groupby("Ciudad")["Nota"].mean()
grupo

Ciudad
Barcelona     3.9
Bogotá        4.2
Concepción    4.8
Santiago      4.5
Valdivia      3.9
Name: Nota, dtype: float64

In [87]:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Nota", "Sexo", "Ciudad"],
    ["Amanda", 21, 4.5, "F", "Santiago"],
    ["Sofía", 22, 4.8, "F", "Concepción"],
    ["Camilo", 30, 3.9, "M", "Valdivia"],
    ["Paula", 19, 4.2, "F", "Santiago"],
    ["David", 30, 3.9, "M", "Bogotá"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

Instrucción 3

In [97]:
grupo_A = np.random.normal(7.2, 0.4, 56)
grupo_B = np.random.gamma(shape=306, scale=0.0229, size=56)

In [98]:
df2 = pd.DataFrame({"nota": grupo_A })
df3 = pd.DataFrame({"nota": grupo_B })

In [127]:
df5 = pd.DataFrame({
    "A": grupo_A,
    "B": grupo_B
})
df5

           A         B
0   7.213928  6.967044
1   7.200176  7.479517
2   7.264482  6.995390
3   6.640783  6.869493
4   6.793181  6.702934
5   6.764252  6.583373
6   7.500305  7.735818
7   7.264847  7.203285
8   7.449560  7.002537
9   7.540186  6.879825
10  7.516085  6.960960
11  7.244291  7.077515
12  7.631163  6.875869
13  7.191190  6.794688
14  7.013581  6.062108
15  7.417568  7.200769
16  6.758125  6.815233
17  6.910511  7.047799
18  7.891027  6.163836
19  7.220023  7.147747
20  7.213802  7.037515
21  6.827879  7.153839
22  7.555592  6.942667
23  7.878185  7.105291
24  7.194549  7.040103
25  7.089523  7.617936
26  7.222139  6.460397
27  7.618403  6.885334
28  7.240657  6.915166
29  7.424065  6.523696
30  7.071688  7.087620
31  6.962934  7.539462
32  7.043188  7.113359
33  7.185827  6.668782
34  7.075536  6.614702
35  6.156423  7.109314
36  7.404488  7.470125
37  6.608672  6.450922
38  6.877357  6.647158
39  7.509299  7.492153
40  7.804829  6.477468
41  7.721993  6.794823
42  7.186785  6.404948
43  7.680508  6.721153
44  7.166558  6.501176
45  6.765738  7.256934
46  6.692593  6.959798
47  6.890109  7.099684
48  6.958921  7.543654
49  7.048190  7.286675
50  6.740946  7.020445
51  7.233077  6.890444
52  7.609027  6.912842
53  6.608379  7.185416
54  7.960421  7.101442
55  6.850673  7.018218

In [116]:
df4 = pd.DataFrame({'Calificacion': np.concatenate([grupo_A, grupo_B]),
                    'Grupo': ['A']*56 + ['B']*56})
df4

     Calificacion Grupo
0        7.213928     A
1        7.200176     A
2        7.264482     A
3        6.640783     A
4        6.793181     A
..            ...   ...
107      6.890444     B
108      6.912842     B
109      7.185416     B
110      7.101442     B
111      7.018218     B

[112 rows x 2 columns]

In [111]:
df2.describe()

            nota
count  56.000000
mean    6.957436
std     0.348931
min     6.062108
25%     6.776304
50%     6.981217
75%     7.121956
max     7.735818

En el grupo A La media de las notas es aproximadamente 6.9. La desviacion estantar es al rededoir de 0.3; la nota mímina es de 6. Miestras el 25% de los estudiantes tienen una nota por encima de 6.7, por un lado, el 50% de los alumnos ronda al rededor d dor 6.9, por el otro. Sólo el 75% de los estudiantes supera una nota de 7.1 y la nota máxima es aproximadamente 7.7.

In [112]:
df3.describe()

            nota
count  56.000000
mean    6.957436
std     0.348931
min     6.062108
25%     6.776304
50%     6.981217
75%     7.121956
max     7.735818

En el grupo A La media de las notas es aproximadamente 6.9. La desviacion estantar es al rededoir de 0.3; la nota mímina es de 6. Miestras el 25% de los estudiantes tienen una nota por encima de 6.7, por un lado, el 50% de los alumnos ronda al rededor d dor 6.9, por el otro. Sólo el 75% de los estudiantes supera una nota de 7.1 y la nota máxima es aproximadamente 7.7.

In [124]:
from scipy import stats

In [128]:
t_stat, p_val = stats.ttest_ind(df["A"], df["B"])

print("Estadístico t:", t_stat)
print("Valor p:", p_val)

KeyError: 'A'

In [125]:
stat, p = shapiro(df2["Calificacion"])

NameError: name 'shapiro' is not defined

In [ ]:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogotá"],
    ["Luis", 30, "Medellín"],
    ["Carlos", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

# CREAR MODULOS Y PAQUETES:

import os
os.makedirs("op", exist_ok=True)

%%writefile op/operaciones.py

# FUNCION LAMBDA
import pandas as pd
x = [1, 2, 3, 4]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(123)

grupo_A = np.random.normal(loc=4.0, scale=0.4, size=40)
grupo_B = np.random.normal(loc=4.3, scale=0.5, size=40)

df = pd.DataFrame({
    "A": grupo_A,
    "B": grupo_B
})

t_stat, p_val = stats.ttest_ind(df["A"], df["B"])

print("Estadístico t:", t_stat)
print("Valor p:", p_val)